travis:
  secure:
    BINSTAR_TOKEN: pJEQNfZQ836VFq3YLZLSXiwp/pPCep2yM2/U6RTSeiyxwc5F9wCd1sSYm9ZEngWZZHjJJ/ZRRtHKGA4gEa9R/9/bd3QCD8yYoUar56zRQMFTRyhnlqpYP2OZU5P1XXcaB9Nsx2u2pMXAgvCT4u4Lkmwn247Y2cqgRnlkQx3Y7MMstkrhnmF9ESOVaq9hH80Kd5TF/Ll56kosJNEe2intKOT5gdR/grDbS1tFlG2OR25EpBMxj0oWLSfm8ClSFaMNOeoj0SYb/+FQ0C/C+GvpiIsUMdqw1M52jh3LmU13xatwrnm7oZRwWhJqjhrKYPFb151qNlXmckX6lPuiiBHrK7NIOnlGFHsN6V9AGepSbFF2bM2OV/wngmXZZ8C6lekfVXcrmkxBZvgrf2iCc8CcRyFNtWSadUd9+i+Cnph3utL+AuuTgxVV0wzxmW/sA1x/E+mtcKXGaiUOlXhRhlmSOtvux/AeBqEMCLMFbGv75Br6H44RKN2jHRjRaFb5Ecbpo7fQRXoQfItSwiGxZpJasv+1MrTvAjGnxCb069gALMuc2PqKVUjQX7oSr5a9FQfkEENwzgDx2XptOYr4K0woFwP6ZXMQNUr3iuS5pPH2Fj2cFa6qOCBY8m+TCeR8WfDdUiQVkf3Fu0aCc6P54tswkTWbmArGD+P3DJIgCtMSJ5o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
