travis:
  secure:
    BINSTAR_TOKEN: YSwDEnhOM+T1r29vHRlKjia4W2/mdrWPOcRPhXNFD1wQP9lHLeKI4W2Ihw0nAordghpmkAb+UR58FMjuJqlFcxQLLD3phLhi8PQqXo0qhDh2mFx35Sv5CDgh+YSV6PcwrTAuyXn7P7fHaCqDudneHd9710dN/QVymmnWUCNReLMqMonyPJsOBXHDHyih+t6cDcg+IznAGEL74BjmyDJ7fk4UOG+ib7vJJRN6GHMAwFra4gELp1rjPJoILAEVk/+Hcq7GSEw+AMQ6HDViJG/rC2Zlun7W4sioJgcLjcNUZ8H8c/oIvx5qNF7cBhOMVDSF309EUSnpqFlxEVRo8kxnE/iRLAbNj8axgrV3jl4jrt5cHCK2EDmJ7BHOnKG9U8j82jwS8WgtE0LuSc0DrrL9MILhdtS40UZD+GI1a7kbUQd6py1Zrqpty+Q98mpUyihyRS/0cV4Gyf1QvBToKLw9wUu2grq2T+M9gJkoG8LRZvS0kREh5yAftBKIJg0lh+IT9UywqwdmR01UkhVppyhnJjg8r9teArqJIdw/tWisnWokASs8X/g061/6/dyTcaygwA8mllk8MM6XWz+j+QOZCYmqSk6s1gcqY/qklU7I1x8GlzT9IrXAFPJGtj4qfn0jjNhM9A09tx/eRWgMOY6oFVJQvRr9yWAXlCOaYk19r8I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
